(function ( win, doc) {
	

	// ESSA FUNÇÃO SERÁ CHAMADA DEPOIS QUE TUDO NA PÁGINA FOR CARREGADO
	function afterDOMContentLoaded() {
		alert("Tudo Carregado!");
	}

	// ESSA FUNÇÃO SERÁ CHAMADA DEPOIS QUE TUDO NA JANELA FOR EXECUTADO
	function afterWindowLoad() {
		alert('Tudo Na Janela Foi Carregado1!');
	}

	// ISSO ADICIONA UM EVENTO NO DOCUMENT DO SITE QUE IRÁ PRIMEIRO CARREGAR TODO OS ELEMENTOS HTML PRA DEPOIS CHAMAR A FUNÇÃO QUE IRÁ EXECUTAR O SCRIPT DA PÁGINA
	doc.addEventListener('DOMContentLoaded', afterDOMContentLoaded, false);

	// ISSO IRÁ ADICIONAR UMA FUNÇÃO NA JANELA DO NAVEGADOR QUE SÓ SERÁ EXECUTADO DEPOIS QUE TUDO NA JANELA FOR CARREGADO
	// ISSO É MUITO UTIL, PRINCIPALMENTE PORQUE IMAGENS CARREGAM SUA TAG NO DOCUMENTO HTML, PORÉM DEPENDENDO DA VELOCIDADE DO NAVEGADOR SEU CARREGAMENTO NA TELA DEMORA UM POUCO MAIS	
	win.addEventListener('load', afterWindowLoad, false);



})( window, document);