( function ( w, d) {
	'use strict';

	// ISSO DEVE SER ESTUDADO PARALELAMENTE É UM MODO DE OTIMIZAÇÃO ESTREMAMENTE IMPORTANTE MAS NO CURSO É MUITO CONFUSO
	// PROCURAR DOCUMENTAÇÃO NA INTERNET
	

})( window, document);

