	
	// CRIA UM NOVO OBJETO NUMBER
	var numero = new Number(140.52324);

	// DETERMINA O NUMERO DE CASA QUE O NUMERO VAI MOSTRAR DEPOIS DA VIRGULA
	document.write(numero.toFixed(2));
	document.write("<br>");

	// RETORNA A QUANTIDADE DE DIGITOS DEFINIDAS PELO PARAMETRO
	// CASO O PARAMETRO SEJA MENOR QUE A QUANTIDADE DE CASAS QUE O NUMERO TENHA ELE RETORNA EM FORMA
	// NOYTAÇÃO CIENTIFICA
	document.write(numero.toPrecision(1));

	// CONVERTE UM NUMERO EM NOTAÇÃO CIENTIFICA
	// OS PARAMETROS DEVEM ESTAR COOMPREENDIDOS ENTRE 0 E 20
	document.write('<br>');
	document.write(numero.toExponential(5));